import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-900 text-slate-50 text-center">
          JANGAN MAIN SLOTT!!!
        </div>
        <Navbar session={session} />
        <Suspense fallback={"Tunggu Sebentar..."}>{children}</Suspense>
        <Toaster />
        <Sonner />
      </body>
    </html>
  );
}
